name: Daily Parking Automation

on:
  schedule:
    - cron: '30 19 * * *'  # Runs at 7:00 AM UTC every day
  workflow_dispatch:     # Optional: Allow manual triggers

jobs:
  automate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Firefox and Geckodriver
        run: |
          # Remove conflicting versions
          sudo rm -f /usr/bin/firefox /usr/local/bin/geckodriver
    
          # Install Firefox ESR (Extended Support Release)
          sudo apt-get update
          sudo apt-get install -y firefox-esr
          
          # Install the correct geckodriver (v0.34.0 works with Firefox ESR)
          wget https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.34.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver
          geckodriver --version

      - name: Run the script
        run: python AutoPark.py
        env:
          LICENSE_PLATE: ${{ secrets.LICENSE_PLATE }}  # Optional: Store sensitive data in Secrets
