name: Daily Parking Automation

on:
  schedule:
    - cron: '30 19 * * *'  # 7:30 AM NZST (7:30 PM UTC)
  workflow_dispatch:

jobs:
  automate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Install Firefox and dependencies
        run: |
          # Add Mozilla PPA for traditional Firefox
          sudo add-apt-repository ppa:mozillateam/ppa -y
          sudo apt-get update
          sudo apt-get install -y firefox
          
          # Set Firefox as default
          sudo update-alternatives --set x-www-browser /usr/bin/firefox
          
          # Install webdriver-manager
          # pip install webdriver-manager

      - name: Run script
        run: python AutoPark.py
        env:
          LICENSE_PLATE: ${{ secrets.LICENSE_PLATE }}
